#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
	. /lib/functions.sh
	config_load drcom
	config_get_bool enabled main enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/bin/drcom-auto-login --daemon
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	return 0
}

once() {
	/usr/bin/drcom-auto-login --once
}

status() {
	/usr/bin/drcom-auto-login --status
}

service_triggers() {
	procd_add_reload_trigger drcom
	procd_add_interface_trigger "interface.*" wan /etc/init.d/drcom-auto-login restart
}
